name: crdt
description: A dart-native implementation of a Conflic-free Replicated Data Type abstraction layer.
version: 1.0.0
homepage: https://github.com/cachapa/crdt

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # no dependencies, no problems

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
